
@tm_host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTUzMTgzNjY1fQ.LNrDy3NPadLwdgNH_500X-EdtE3ROZkvzq6W2RlUKFM

### Login : Should return 200
POST {{tm_host}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### GET /tournament : Should return 200
#   Expected output is a

{{tm_host}}/tournaments


### POST /tournaments : Should return 200
POST {{tm_host}}/tournaments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pera",
  "signUpExpiration": null,
  "maxTeams": 4,
  "sport": 2,
  "isPublic": true,
  "teams": [
  ]
}

###
{{tm_host}}/tournaments/4
###
{{tm_host}}/profile
Authorization: Bearer {{token}}
###

POST {{tm_host}}/signup
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###
POST {{tm_host}}/tournaments/3/sub
Authorization: Bearer {{token}}

###
POST {{tm_host}}/tournaments/3/unsub
Authorization: Bearer {{token}}
###
POST {{tm_host}}/tournaments/1/start
Authorization: Bearer {{token}}
###
POST {{tm_host}}/tournaments
Authorization: Bearer {{token}}

{
  "name": "auth test",
  "maxTeams": 4,
  "rounds": 2
}

###

PATCH {{tm_host}}/tournaments/1/edit
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Patched again 2"
}

###

PATCH {{tm_host}}/tournaments/1/match/17
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "homeTeamScore": 3,
  "awayTeamScore": 3
}

###
DELETE {{tm_host}}/tournaments/9
Authorization: Bearer {{token}}


###
postgres://hhftkujkhjkosw:0bc94d41d8eb54f39fed104e98ac9b6acae510fabf98295749379fc55c9cf8f4@ec2-54-247-85-251.eu-west-1.compute.amazonaws.com:5432/de5rnl6a92hbv


